### ISSUE TITLE
aggressiveUserFullScreenExperience on Monterey results in unresponsive Mac

### ISSUE THREAD

**Issue by VicFromFrance** [macadmins/nudge#381] opened 2022-07-18 09:40 UTC
When using aggressiveUserFullScreenExperience option (true), at first everything looks fine, but when clicking on the 'Update Device' button the Mac gets unresponsive and only a hard reboot fixes this. 

Can reproduce this issue on Monterey 12.2 and Monterey 12.4. Big Sur works fine tough.

It happens not directly, but after the Mac starts screensaver and locks the Mac.

![MacError](https://user-images.githubusercontent.com/109369092/179485144-98b20b31-e046-409b-8f1d-95fe2a25376b.png)
.

**Comment by erikng** [comment] 2022-07-18 14:44
Are you using a custom action for Update Device? This looks like Nudge has crashed.

**Comment by mani2care** [comment] 2022-07-20 04:35
I hope user having multiple desktop and you may need to swipe right or left to check the home nudge screen

**Comment by VicFromFrance** [comment] 2022-07-22 09:03
> Are you using a custom action for Update Device? This looks like Nudge has crashed.

No I have not.

**Comment by VicFromFrance** [comment] 2022-07-22 09:03
> I hope user having multiple desktop and you may need to swipe right or left to check the home nudge screen

This do not fix it. Full screen experience overrides it.

**Comment by bradtchapman** [comment] 2022-07-23 00:01
I'm seeing this too.  I installed Nudge on an M1 and upgraded from Big Sur to Monterey.  

Let it sit at the login screen for a while.  As soon as I logged in, Nudge prompted for an update.  When I clicked "Update Now," this exact thing happened to me.

Interestingly, if I swipe the trackpad from the right edge, I can just make out the Notification Center opening up from the right side of the screen.  If I swipe up four fingers, I can see all the windows and the Spaces manager.

**Comment by bradtchapman** [comment] 2022-07-23 08:07
Update: I have been able to reproduce this on a Mac running 12.3.1.  NOTE: the steps to reproduce and the refresh time are not intended to be a reflection of our environment; they are merely a way to save time in reproducing the actual bug.

Steps to reproduce: 
1. Install Nudge (don't install a profile or JSON yet).
2. Set any macOS screensaver to start in 1 minute.
3. Set at least one hot corner to "start screen saver."
4. Check your Security & Privacy settings and set [x] require password Immediately after sleep or screen saver begins.
5. Deploy a Nudge profile with any messaging you like.  For configuration parameters, use a short refresh cycle (i.e.: 60 seconds), a target OS newer than the current one, the aggressive user experience with full screen blur, and an expiration in the past (enough to trigger the aggressive behavior).
6. Ignore the first nudge prompt (or click Update Now).
7. Start the screensaver using the Hot Corner.
8. Wait at least 5-6 full refresh cycles for Nudge (i.e.: 5-6 minutes).
9. Unlock the computer from the screensaver.
10. Nudge appears.  Click 'Update Now.'

If it doesn't work the first time, repeat steps 7-10 at least two more times (lock, wait, unlock, click).

I've been able to reproduce this 3 separate times now.

**Comment by bradtchapman** [comment] 2022-07-23 16:08
@erikng - please see above to reproduce issue.  Seems that a Mac left locked in screensaver for a while could result in Nudge leaving the FSblur on permanently, locking the user out.

**Comment by bradtchapman** [comment] 2022-07-24 23:24
@VicFromFrance - I was able to reproduce your issue btw.

**Comment by VicFromFrance** [comment] 2022-07-25 06:04
> @VicFromFrance - I was able to reproduce your issue btw.

Yes, I'm following this with great interest. We were on the brink of rolling out Nudge but this stops it all. Do you now use Nudge without the aggressiveUserFullScreenExperience option? Is it enough for your users?

**Comment by bradtchapman** [comment] 2022-07-25 06:56
I have not rolled it out yet, but at this stage I would opt not to use that feature.  A colleague of mine deployed Nudge for the first time to a fleet of 500 Macs and got >90% compliance in under 2 weeks.  That's huge, and I'm hoping for similar success with 20x as many devices.

**Comment by erikng** [comment] 2022-07-25 12:54
This is a brand new feature only available with the most recent version of Nudge. I would disable it for now (Uber, Facebook and Google do not use this feature) and you will be very happy with your success for having users install updates. 

I will unlikely have time to look at it for at least a few days. My immediate thought is Nudge should not invoke any of its logic during the screensaver and/or Lock Screen.

**Comment by bradtchapman** [comment] 2022-07-25 14:37
@erikng : no problem, it's not urgent and I understand that the feature is still new.  It's definitely nice to have.  I'm just excited to have reproduced the issue so quickly.

**Comment by erikng** [comment] 2022-07-26 15:52
I think I've figured out what the issue is, but I didn't recreate it as I was coding new fixes. I think it has to do with the "front most application" being nil when coming out of the screen saver and Nudge not able to handle this.

I'm using `open -b com.apple.ScreenSaver.Engine` to trigger the screen saver rather than a hot corner.

I'm attempting to create a new pre-release version of Nudge but I'm worried it's going to fail since I've now added new Xcode 14 features and GitHub still doesn't have a CI runner that contains Xcode 14.

**Comment by erikng** [comment] 2022-07-26 16:35
Please https://github.com/macadmins/nudge/releases/tag/v1.1.8.81421

**Comment by bradtchapman** [comment] 2022-07-26 23:12
So far this build seems to be behaving correctly.  I've observed:

- When I'm in another app, Nudge steals focus and blurs the whole background.
- When I am unlocking after a screensaver, the background is not blurred*
- *One time it was blurred after unlock, but clicking "Update Now" made the blurry background go away.

**Comment by erikng** [comment] 2022-08-01 17:33
I'm going to close this since v1.1.8 is coming out today. If anyone experiences issues, please create a new ticket.

**Closed by erikng** 2022-08-01 17:33 UTC
