### ISSUE TITLE
Can't get any version (above 2.0.1.81717) working?

### ISSUE THREAD

**Issue by theboyk** [macadmins/nudge#624] opened 2024-07-31 19:31 UTC
When I install any version of Nudge, above 2.0.1.81717, Nudge no longer works.

I ran into this issue under 14.5 (and just updated to 14.6 and still have the issue). I'm on an Apple MacBook Pro (M1 Pro), running as an admin user.

I've tested all version above 2.0.1.81717, up to 2.0.5.81760, and having the same issue with all releases.

When I attempt to trigger Nudge via:

`/Applications/Utilities/Nudge.app/Contents/MacOS/Nudge`

Nudge just hangs. Only way out is to force-quit Nudge.

One thing I've noticed is that, when installing any of the versions above 2.0.1.81717, the following file is no longer being created:

`/Users/myusername/Library/Preferences/com.github.macadmins.Nudge.plist `

And if I try and run:

`defaults delete ~/Library/Preferences/com.github.macadmins.Nudge.plist`

I get the following in return (even if the file is actually there, from running Nudge 2.0.1.81717):

`Domain (/Users/myusername/Library/Preferences/com.github.macadmins.Nudge.plist) not found.`

I've attached console output when I try and trigger Nudge, along with my test .mobileconfig (very basic, just for testing). The .mobileconfig is being deployed via Jamf Now (also tested by manually installing).

Hoping someone might be able to help?

Thanks,
Kristin.

[nudge-files.zip](https://github.com/user-attachments/files/16446343/nudge-files.zip)

**Comment by ggeerraalldd** [comment] 2024-07-31 20:18
Hi Kristin,

Starting with [Nudge 2.0.2.81720](https://github.com/macadmins/nudge/releases/tag/v2.0.2.81720), by default there is a random delay when Nudge is triggered (either manually or via the launchagent). The reason for that is in the release notes linked above. In your log, near the bottom it reports that a delay of 482 seconds was being applied before Nudge activated.

There are a number of [new command line arguments](https://github.com/macadmins/nudge/wiki/Command-Line-Arguments#disable-random-delay--disable-random-delay) that will help you test Nudge 2.x, including disabling the random delay, spoofing the OS version you're checking against, spoofing the hardware you're checking against, and more.

In your case, if you want to see what Nudge would display on your computer if it was running a prior version of Sonoma, you can enter this command in Terminal to disable the delay and pretend the current OS is 14.4.1:

`/Applications/Utilities/Nudge.app/Contents/MacOS/Nudge -simulate-os-version "14.4.1" -disable-random-delay`

**Comment by theboyk** [comment] 2024-07-31 20:51
OK, when I run the above command, how long should I have to wait until the Nudge UI is triggered? I assumed it would be "right away", but maybe it's tied to the LaunchAgent (30 mins)? I ask, because I've tried that (add setting randomDelay to False in the .mobileconfig), but I still don't get the Nudge UI opening (though, I have to admit, I haven't waited for 30 mins to see if it triggers).

So, when it didn't trigger the UI quickly, I assumed that was unrelated to my issue?

The only way I seem to get the UI to show, is to run that command (or similar), and then launch the Nudge.app (manually, via Finder)?

**Comment by erikng** [comment] 2024-07-31 22:38
Correct. This is the intended behavior per the release notes. In production, you also do not want your users all getting nudged at the exact same time. Imagine if there was a bug and throughout all floors of all offices, everyone receives it at the same time.

You can continue to use the CLI option for your testing, but the expectation is randomDelay will occur. You should be getting it immediately with the mobileconfig though. That sounds like a config issue within your MDM. I am going to close this topic as it is expected behavior. Please come to the nudge slack channel if you have more feedback on this.

**Closed by erikng** 2024-07-31 22:38 UTC
