### ISSUE TITLE
JSON Schema for Jamf to create Profile to configure Nudge

### ISSUE THREAD

**Issue by MatGriffin** [macadmins/nudge#119] opened 2021-02-19 13:54 UTC
Feature suggestion for when Nudge can be configured via MDM delivered Profile.
A JSON schema that can be used in Jamf Applications & Custom settings payload so the config of the Profile for nudge is directly in Jamf UI.

**Comment by erikng** [comment] 2021-02-19 21:47
Jamf does not follow the MDM profile spec so this will not be possible. Please submit a ticket to Jamf asking them to follow the spec. 

This is a dupe of another ticket. Closing.

**Comment by erikng** [comment] 2021-02-19 21:48
https://github.com/macadmins/nudge/issues/106

**Closed by erikng** 2021-02-19 21:47 UTC
