### ISSUE TITLE
Feature Request: Add logging capability into the main app

### ISSUE THREAD

**Issue by kevinmcox** [macadmins/nudge#443] opened 2023-01-20 22:20 UTC
What would y'all think about moving the functionality of the Nudge Logger into the core app?

This could default to off/false but then be enabled with a configuration option if desired.

Benefits would be that admins would no longer need to deploy the separate Nudge Logger package which requires managing the Login Item that displays as only "log" in System Settings for users.

**Comment by erikng** [comment] 2024-05-17 16:46
The problem is where would the log go? Nudge doesn't run as root whereas the logger package does.

**Comment by erikng** [comment] 2024-05-31 21:36
I'm going to close this. Nudge natively uses Apple's Unified Logging, a best practice by Apple and Swift. Unfortunately, Apple has never provided a good way for logging these files to disk for consumption. This is a common issue for enterprise admins and you see similar style logic used by jamf, airwatch, etc to get logs onto disk.

I don't plan on writing out to a local area for all of these logs, so I'm going to close this. There are many tools, like osquery, that allow you to capture unified logging for more than nudge, so if you do not like the daemon method, I would recommend investing into tools like these so you can get data for more than nudge.

**Closed by erikng** 2024-05-31 21:36 UTC
Labels: unlikely-to-implement
