### ISSUE TITLE
Bug: Nudge fails to open update window

### ISSUE THREAD

**Issue by richardpurves** [macadmins/nudge#398] opened 2022-09-01 18:10 UTC
Nudge 1.1.8.81422
macOS 13.0b6

Clicking the "Update Device" button results in an error stating "The file can't be found".

<img width="960" alt="Screenshot 2022-09-01 at 11 08 43 AM" src="https://user-images.githubusercontent.com/61799165/187983714-4ef711bc-b85a-402e-9ada-7bb532e81f46.png">

Possible hard coded file path for system preferences?

**Comment by flammable** [comment] 2022-09-01 18:13
What do you have set for `actionButtonPath`?

**Comment by pro4tlzz** [comment] 2022-09-01 18:17
I have reproduced this error on 
Nudge 1.1.8.81422
macOS 13.0b6

`actionButtonPath` isn't set

**Comment by richardpurves** [comment] 2022-09-01 18:24
Yep, I'm not setting that key at all.

It was working nicely when it was set to open jamf self service but i'm testing different config behaviour at the moment.

**Comment by pro4tlzz** [comment] 2022-09-01 18:27
Code related to opening system preferences seems to be here https://github.com/macadmins/nudge/blob/b77495ce405d2166a72a37f5484e8b84e46e9b55/Nudge/Utilities/Utils.swift#L843

**Comment by flammable** [comment] 2022-09-01 18:30
That makes sense. `/System/Library/PreferencePanes/SoftwareUpdate.prefPane` doesn't exist anymore.

**Comment by erikng** [comment] 2022-09-02 00:18
So what's the new path? I haven't particularly paid attention to Ventura with regards to nudge.

**Comment by adamselbycapitalone** [comment] 2022-09-02 00:59
`open x-apple.systempreferences:com.apple.Software-Update-Settings.extension` per [rtrouton](https://gist.github.com/rtrouton)/[Open Ventura System Preferences to desired locations.txt](https://gist.github.com/rtrouton/87806d7ccdd8db1be2836fd7613b2e63)

**Comment by adamselby** [comment] 2022-09-02 01:01
Per [Open Ventura System Preferences to desired locations.txt](https://gist.github.com/rtrouton/87806d7ccdd8db1be2836fd7613b2e63) its `x-apple.systempreferences:com.apple.Software-Update-Settings.extension`.

**Comment by colorenz** [comment] 2022-09-11 20:47
That works in Big Sur, Monterey and Ventura:

`open 'x-apple.systempreferences:com.apple.preferences.softwareupdate'`

**Comment by pro4tlzz** [comment] 2022-09-12 09:16
> That works in Big Sur, Monterey and Ventura (tested in Beta 7):
> 
> `open 'x-apple.systempreferences:com.apple.preferences.softwareupdate'`

Thanks, I might make a PR for this

**Comment by erikng** [comment] 2022-09-12 11:53
Closing this

**Closed by erikng** 2022-09-12 11:53 UTC
