### ISSUE TITLE
Feature Request: Allow the blurred background experience to honor AcceptableApplicationBundleIDs 

### ISSUE THREAD

**Issue by jshirle2** [macadmins/nudge#388] opened 2022-08-19 17:13 UTC
Currently blurred backgrounds are a little too aggressive for my organization. Specifically we want the ability to prevent Nudge from doing anything if the user is in a teams/zoom meeting. This could be accomplished by adding a key (True/False) that would honor acceptableApplicationBundleIDs for the blurred background when in aggressive mode.

**Comment by crizchun** [comment] 2022-10-01 14:00
@jshirle2 
I've run into this exact issue with **aggressiveUserFullScreenExperience**. 
So far, I've found no way to fully prevent it while on a zoom call. 
If zoom stays the foremost window 100% of the time, I've found that the _acceptableApplicationBundleIDs_ for zoom will work!
But the problem is that almost all users will move zoom out of the way to continue working, while still being on their zoom call. 
Every combination of settings I've tried (including enabling _acceptableScreenSharingUsage_ ) just wouldn't prevent the blurred background. 

My question has been, 
is this the expected behavior?, or is there a way to make _aggressiveUserFullScreenExperience_ not kick in while on a zoom call . . .

**Comment by erikng** [comment] 2022-10-01 17:14
You're essentially asking for me to be able to detect that a user has a zoom session active but it's not their active application, which means the only real thing I could do here is see if zoom is in memory. 

I have ZERO intentions of doing that. Sorry.

**Comment by crizchun** [comment] 2022-10-01 19:07
Totally understood, you are the Nudge Creator after-all. 

I'd recommend some better clarity in the NudgeWiki: 
https://github.com/macadmins/nudge/wiki/optionalFeatures
for  _aggressiveUserFullScreenExperience_ and how it works with _acceptableApplicationBundleIDs_, _acceptableCameraUsage_, _acceptableScreenSharingUsage_, and _acceptableAssertionUsage_ 
with regard to the way zoom is used, and being the foremost window vs. not being the foremost window.

I can't imagine we're the only people who _assumed_ it would prevent aggressivemode while on a zoom call, regardless of zoom not being their active window.

**Comment by shannonpasto** [comment] 2024-04-12 03:34
Hi all.

Seeing this as well. The aggressive blurred screen honours anything in acceptableApplicationBundleIDs if they are the front most app. Perhaps an alternative solution to doing [memory checking](https://github.com/macadmins/nudge/issues/388#issuecomment-1264427185) would be to honour acceptableAssertionApplicationNames as this seems to work in the initial, approaching and imminent cycles.

Cheers

**Comment by erikng** [comment] 2024-05-17 16:54
I still don't think I want to do this. When you get into blurred mode it's because you are now in "aggressive" mode. At this point, we shouldn't be honoring very many things within Nudge to encourage the user to update with the highest level of annoyance.

**Comment by erikng** [comment] 2024-05-31 21:40
I'm going to close this as I have no desire to check for applications in memory. I want to use native apple APIs and shell out only when I absolutely have to. If the users find the blurring too aggressive, they should have updated their devices. This is the stick and carrot approach.

The code base will continue to get exponentially harder to maintain if I allow every small use case to be designed and accounted for.

**Closed by erikng** 2024-05-31 21:40 UTC
