### ISSUE TITLE
`fallbackLanguage` and `forceFallbackLanguage` behaviour issue

### ISSUE THREAD

**Issue by philsaino** [macadmins/nudge#582] opened 2024-05-30 10:35 UTC
Hi, 
I have a problem with the behaviour of the keys `fallbackLanguage` and `forceFallbackLanguage` in the Nudge Config Profile. 

I've set three languages in `updateElement - Dictionary`  in the `updateElements` key: 

- en (English)
- es (Spanish)
- pt (Portuguese)

With `fallbackLanguage` set to `en` and `forceFallbackLanguage` set to `true`, if the language set on the mac is `_es_` or `_pt_`, Nudge displays always personalised `_en_ `localisation: seems that the program does not recognise the language. 

If i put `false` on `forceFallbackLanguage`, I have the expected behaviour but if on the mac is set up a language **_different_** from the three mentioned above Nudge does not display the `fallbackLanguage` I've set up but shows the standard localised dictionary. 

I have the necessities to display the fallback Language in **_english_** when on the mac is set a language different from English, Spanish or Portuguese. 

Anyone could help me?

**Comment by erikng** [comment] 2024-05-30 13:27
Could you confirm for me if when everything is setup properly on the config if a fourth language (not in your config) is used, that force fallback works as intended?

If so, that implies that only those 2 other languages are broken in the code base and will simplify what code I have to look at for the potential bug.

**Comment by philsaino** [comment] 2024-05-30 14:14
> Could you confirm for me if when everything is setup properly on the config if a fourth language (not in your config) is used, that force fallback works as intended?
> 
> If so, that implies that only those 2 other languages are broken in the code base and will simplify what code I have to look at for the potential bug.

Hi, thanks for your reply. 

This is the detailed behaviour based on the different settings and tests I made.

As I said, I've configured three different languages with custom texts in `updateElement - Dictionary` in the `updateElements` key:

- en (English)
- es (Spanish)
- pt (Portuguese)

**### Case 1**
Config profile configuration: 
`fallbackLanguage` set to **`en`**
`forceFallbackLanguage` set to **`true`**

The results with the languages set up on the mac are: 

English --> Mod text English
Spanish --> Mod text English
Portuguese --> Mod text English
Italian (not in the config) --> Mod text English

**### Case 2**
Config profile configuration: 
`fallbackLanguage` set to **`en`**
`forceFallbackLanguage` set to **`false`**

The results with the languages set up on the mac are: 

English --> Mod text English
Spanish --> Mod text Spanish
Portuguese --> Mod text Portuguese
Italian (not in the config) --> Nudge Default text Italian

Hope this help to understand the problem, thanks a lot

**Comment by philsaino** [comment] 2024-05-30 14:23
Other infos, if needed: 
I'm running latest Nudge 1.1.16.81564 and MacOS Sonoma 14.5.
I've tried previous versions of Sonoma with the same behaviour.

**Comment by erikng** [comment] 2024-05-30 21:30
This will be fixed in the next 2.0 pre-release https://github.com/macadmins/nudge/commit/febf07351cca935ffb81c200e27825259d6703c3

**Closed by erikng** 2024-05-30 21:30 UTC
Labels: need-to-investigate
