### ISSUE TITLE
Feature Request: dynamic requiredMinimumOSVersion

### ISSUE THREAD

**Issue by lorenz-qbees** [macadmins/nudge#474] opened 2023-04-11 15:10 UTC
We implemented Nudge with Jamf Pro and are really happy with this setup.

Since we always want to use the latest macOS stable release it would be great to have a dynamic requiredMinimumOSVersion which provides the latest version.

In addition a dynamic requiredInstallationDate would be awesome. Something like "X days after release".

This would help to avoid changing the version string and install date all the time.

**Comment by aysiu** [comment] 2023-04-11 15:16
I think a lot of people would love this feature. I'm not sure it's that straightforward, though. Would probably need some source-of-truth database to determine when the update came out. Is that stored locally? If the update came out on the 1st of the month, but your Mac was offline until the 12th of the month, would macOS still know that update came out on the 1st? There may also be cases in which (because of specific CVEs the update patches) an override would be necessary.

**Comment by erikng** [comment] 2023-06-16 14:19
This is a dupe of many requests. I have no plans still to do this but if that changes, I will update the info on the original request.

**Closed by erikng** 2023-06-16 14:19 UTC
