### ISSUE TITLE
to better handle Macs that have been completely turned off to allow user a short grace period to install the OS update without interruption

### ISSUE THREAD

**Issue by Lotusshaney** [macadmins/nudge#496] opened 2023-05-25 14:55 UTC
There is currently a grace period feature but during this grace period there are no prompts at all. This would be a request to allow users additional time if they’ve not been able to acknowledge or interact with Nudge past the Required Install Date. This is for situations where a user comes back from vacation or has multiple computers and hasn’t had a chance to update the other computers that may be in the office or at home.

**Comment by erikng** [comment] 2023-06-16 15:20
This is a dupe of https://github.com/macadmins/nudge/issues/438

**Closed by erikng** 2023-06-16 15:21 UTC
